# Generated by Django 5.0.6 on 2025-07-17 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('duracion', models.IntegerField(verbose_name='Duración (horas)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=20, verbose_name='Nivel')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del Curso')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'CONVOCATORIA',
                'verbose_name_plural': 'CONVOCATORIAS',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
