# Generated by Django 5.0.6 on 2025-07-17 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave de Actividad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(blank=True, help_text='Describe detalladamente la actividad', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso relacionado')),
            ],
            options={
                'verbose_name': 'Actividad del Curso',
                'verbose_name_plural': 'Actividades de Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
